<a href="https://colab.research.google.com/github/Gnanamrutha2007/numpy-practice/blob/main/numpy_maths.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
# Basic Mathermatics
a=np.array([1,2,3,4])
print(a)
a+2
a-2
a/2
a*2

b=np.array([1,0,0,1])
b+a
a**2

#take the sin
np.sin(a)

#cos
np.cos(a)

[1 2 3 4]


array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
###LINEAR ALGEBRA
a=np.full((2,3),2)
print(a)

b=np.ones((3,3))
print(b)

np.matmul(a,b)

#find the determinant
c=np.identity(3)
np.linalg.det(c)


[[2 2 2]
 [2 2 2]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


np.float64(1.0)

In [ ]:
import numpy as np
###Statistics
stats=np.array([[1,2,3],[4,5,6]])

np.min(stats,axis=1) #1 means columns

array([1, 4])

In [ ]:
np.min(stats,axis=0) #0 means rows

np.max(stats,axis=1)

np.sum(stats)

np.int64(21)

In [ ]:
### REORGANIZING ARRAYS

before = np.array([[1,2,3,4],[4,5,6,7]])
print(before)
before.shape

after=before.reshape((2,2,2))
print(after)

#vertically stacking vectors

v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2,v2,v2])

#horizontal stacking vectors

h1=np.zeros((2,2))
h2=np.ones((2,4))

np.hstack((h1,h2))


[[1 2 3 4]
 [4 5 6 7]]
[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.]])

MISCELLANEOUS-


In [9]:
#load data from file.

with open("data.txt", "w") as f:
    f.write("1,2,3\n")
    f.write("4,5,6\n")
    f.write("7,8,9\n")
filedata=np.genfromtxt('data.txt', delimiter=',')
filedata=filedata.astype('int32') #this copy's the filedata into integer.
filedata

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [13]:
### Boolean Masking and Advanced indexing

filedata>3   # gives true or false for numbers greater than 3


array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [14]:
filedata[filedata>4] #gives only valuse greater then 4.


array([5, 6, 7, 8, 9], dtype=int32)

In [15]:
#you can index with a list in numpy
a=np.array([1,2,3,4,5,6,7,8])
a[[1,2,5]]

array([2, 3, 6])

In [16]:
np.any(filedata>5,axis=0)

array([ True,  True,  True])

In [18]:
((filedata>5) & (filedata<8))

array([[False, False, False],
       [False, False,  True],
       [ True, False, False]])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')