In [30]:
import numpy as np
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
#print array
print(a)

#get dimension
a.ndim

#get shape
a.shape

#get itemsize
a.itemsize

#get a specific element [r,c]
a[1,-2]

#get total size
a.size

#get a specific row
a[0,:]

#get datatype
a.dtype

#we can customize datatype
b=np.array([1,2,3], dtype='int16')
b.dtype

#get a specific colum
a[:,2] # :->take all rows , 2->take column number 2 i.e, from every row give me column 2.

# [start index: endindex : stepsize]
a[0,1:6:2]

#change element
a[1,5]=20
print(a)

a[:,2]=[1,2]
print(a)

#3D example
c=np.array([[[1,2],[3,4]],[[4,5],[7,6]]])
print(c)
c[0,1,0]

#INTIALIZING DIFFRENT TYPE OF ARRAYS:

#All 0s matrix
np.zeros((2,3))

#All ones matrix
np.ones((4,2,2) ,dtype='int16')

#any other number
np.full((2,2),99,dtype='float32')

#Any other number (full_like)
np.full_like(a,4)

#Random decimal numbers
np.random.rand(4,2)
np.random.random_sample(a.shape)

#Random integer values
np.random.randint(4,7,size=(3,3))

#the identity matrix
np.identity(5)

#repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)
#axis 0 means it repeats rows and 1 means coloums.

#1st question
output=np.ones((5,5))
print(output)

z=np.zeros((3,3))
print(z)
z[1,1]=9
print(z)
output[1:4,1:4]=z
print(output)

#copying array
a=np.array([1,2,3])
c=a;
c[0]=100 #I changed in c, but even a got affected.
print(a)

b=a.copy() #here we are copying a into b.
b[1]=50 #even after making change in b there is not chnage in a.
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[[1 2]
  [3 4]]

 [[4 5]
  [7 6]]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[100   2   3]
[100   2   3]
