In [ ]:
import numpy as np
# Basic Mathermatics
a=np.array([1,2,3,4])
print(a)
a+2
a-2
a/2
a*2

b=np.array([1,0,0,1])
b+a
a**2

#take the sin
np.sin(a)

#cos
np.cos(a)

[1 2 3 4]
[[2 2 2]
 [2 2 2]]


In [ ]:
###LINEAR ALGEBRA
a=np.full((2,3),2)
print(a)

b=np.ones((3,3))
print(b)

np.matmul(a,b)

#find the determinant
c=np.identity(3)
np.linalg.det(c)


[[2 2 2]
 [2 2 2]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


np.float64(1.0)

In [7]:
import numpy as np
###Statistics
stats=np.array([[1,2,3],[4,5,6]])

np.min(stats,axis=1) #1 means columns

array([1, 4])

In [9]:
np.min(stats,axis=0) #0 means rows

np.max(stats,axis=1)

np.sum(stats)

np.int64(21)

In [18]:
### REORGANIZING ARRAYS

before = np.array([[1,2,3,4],[4,5,6,7]])
print(before)
before.shape

after=before.reshape((2,2,2))
print(after)

#vertically stacking vectors

v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2,v2,v2])

#horizontal stacking vectors

h1=np.zeros((2,2))
h2=np.ones((2,4))

np.hstack((h1,h2))

[[1 2 3 4]
 [4 5 6 7]]
[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.]])